# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/MMMU --model msillm_quality_3 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_3/images/MMMU > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_3/MMMU.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/MMMU --model msillm_quality_2 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_2/images/MMMU > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_2/MMMU.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/MMMU --model msillm_quality_1 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_1/images/MMMU > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_1/MMMU.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/MMMU --model msillm_quality_vlo2 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_vlo2/images/MMMU > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_vlo2/MMMU.txt

# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/POPE --model msillm_quality_3 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_3/images/POPE > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_3/POPE.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/POPE --model msillm_quality_2 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_2/images/POPE > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_2/POPE.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/POPE --model msillm_quality_1 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_1/images/POPE > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_1/POPE.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/POPE --model msillm_quality_vlo2 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_vlo2/images/POPE > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_vlo2/POPE.txt
python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/POPE --model msillm_quality_5 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_5/images/POPE > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_5/POPE.txt

# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/MMBench --model msillm_quality_3 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_3/images/MMBench > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_3/MMBench.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/MMBench --model msillm_quality_2 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_2/images/MMBench > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_2/MMBench.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/MMBench --model msillm_quality_1 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_1/images/MMBench > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_1/MMBench.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/MMBench --model msillm_quality_vlo2 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_vlo2/images/MMBench > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_vlo2/MMBench.txt

# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/COCO --model msillm_quality_3 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_3/images/COCO > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_3/COCO.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/COCO --model msillm_quality_2 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_2/images/COCO > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_2/COCO.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/COCO --model msillm_quality_1 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_1/images/COCO > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_1/COCO.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/COCO --model msillm_quality_vlo2 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_vlo2/images/COCO > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_vlo2/COCO.txt


# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/SEEDBench_IMG --model msillm_quality_3 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_3/images/SEEDBench_IMG > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_3/SEEDBench_IMG.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/SEEDBench_IMG --model msillm_quality_2 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_2/images/SEEDBench_IMG > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_2/SEEDBench_IMG.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/SEEDBench_IMG --model msillm_quality_1 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_1/images/SEEDBench_IMG > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_1/SEEDBench_IMG.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/SEEDBench_IMG --model msillm_quality_vlo2 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_vlo2/images/SEEDBench_IMG > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_vlo2/SEEDBench_IMG.txt
python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/SEEDBench_IMG --model msillm_quality_5 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_5/images/SEEDBench_IMG > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_5/SEEDBench_IMG.txt

# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/GQA_TestDev_Balanced --model msillm_quality_3 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_3/images/GQA_TestDev_Balanced > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_3/GQA_TestDev_Balanced.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/GQA_TestDev_Balanced --model msillm_quality_2 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_2/images/GQA_TestDev_Balanced > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_2/GQA_TestDev_Balanced.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/GQA_TestDev_Balanced --model msillm_quality_1 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_1/images/GQA_TestDev_Balanced > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_1/GQA_TestDev_Balanced.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/GQA_TestDev_Balanced --model msillm_quality_vlo2 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_vlo2/images/GQA_TestDev_Balanced > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_vlo2/GQA_TestDev_Balanced.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/GQA_TestDev_Balanced --model msillm_quality_5 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_5/images/GQA_TestDev_Balanced > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_5/GQA_TestDev_Balanced.txt

# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/MME_convert --model msillm_quality_3 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_3/images/MME_mid > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_3/MME_mid.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/MME_convert --model msillm_quality_2 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_2/images/MME_mid > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_2/MME_mid.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/MME_convert --model msillm_quality_1 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_1/images/MME_mid > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_1/MME_mid.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/MME_convert --model msillm_quality_vlo2 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_vlo2/images/MME_mid > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_vlo2/MME_mid.txt
python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/MME_convert --model msillm_quality_5 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_5/images/MME_mid > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_5/MME_mid.txt

# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/OCRBench --model msillm_quality_3 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_3/images/OCRBench > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_3/OCRBench.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/OCRBench --model msillm_quality_2 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_2/images/OCRBench > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_2/OCRBench.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/OCRBench --model msillm_quality_1 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_1/images/OCRBench > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_1/OCRBench.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/OCRBench --model msillm_quality_vlo2 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_vlo2/images/OCRBench > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_vlo2/OCRBench.txt
python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/OCRBench --model msillm_quality_5 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_5/images/OCRBench > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_5/OCRBench.txt

# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/ScienceQA_VAL --model msillm_quality_3 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_3/images/ScienceQA_VAL > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_3/ScienceQA_VAL.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/ScienceQA_VAL --model msillm_quality_2 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_2/images/ScienceQA_VAL > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_2/ScienceQA_VAL.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/ScienceQA_VAL --model msillm_quality_1 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_1/images/ScienceQA_VAL > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_1/ScienceQA_VAL.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/ScienceQA_VAL --model msillm_quality_vlo2 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_vlo2/images/ScienceQA_VAL > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_vlo2/ScienceQA_VAL.txt
# python eval_folder_example.py /data/zhangzf2505/VLMEvalKit/LMUData/images/ScienceQA_VAL --model msillm_quality_5 --save_path /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_vlo2/images/ScienceQA_VAL > /data/zhangzf2505/VLMEvalKit/CompressData/ILLM/ILLM_vlo2/ScienceQA_VAL.txt


# python eval_folder_example.py /data/zhangzf2505/COCODataset/train2017 --model msillm_quality_3 --save_path /data/zhangzf2505/COCODataset/ILLM/ILLM_3/images > /data/zhangzf2505/COCODataset/ILLM/ILLM_3/COCO.txt
# python eval_folder_example.py /data/zhangzf2505/COCODataset/train2017 --model msillm_quality_1 --save_path /data/zhangzf2505/COCODataset/ILLM/ILLM_1/images > /data/zhangzf2505/COCODataset/ILLM/ILLM_1/COCO.txt
# python eval_folder_example.py /data/zhangzf2505/COCODataset/train2017 --model msillm_quality_2 --save_path /data/zhangzf2505/COCODataset/ILLM/ILLM_2/images > /data/zhangzf2505/COCODataset/ILLM/ILLM_2/COCO.txt
