python eval_folder_example.py /data/zhangzf2505/Infinity/dataset/CLIC_2020_768 --model msillm_quality_3 --save_path /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/CLIC_768_3 > /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/CLIC_768_3.txt
python eval_folder_example.py /data/zhangzf2505/Infinity/dataset/CLIC_2020_768 --model msillm_quality_2 --save_path /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/CLIC_768_2 > /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/CLIC_768_2.txt
python eval_folder_example.py /data/zhangzf2505/Infinity/dataset/CLIC_2020_768 --model msillm_quality_1 --save_path /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/CLIC_768_1 > /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/CLIC_768_1.txt
python eval_folder_example.py /data/zhangzf2505/Infinity/dataset/CLIC_2020_768 --model msillm_quality_vlo2 --save_path /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/CLIC_768_vlo2 > /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/CLIC_768_vlo2.txt

python eval_folder_example.py /data/zhangzf2505/Infinity/dataset/Kodak_512 --model msillm_quality_3 --save_path /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Kodak_512_3 > /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Kodak_512_3.txt
python eval_folder_example.py /data/zhangzf2505/Infinity/dataset/Kodak_512 --model msillm_quality_2 --save_path /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Kodak_512_2 > /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Kodak_512_2.txt
python eval_folder_example.py /data/zhangzf2505/Infinity/dataset/Kodak_512 --model msillm_quality_1 --save_path /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Kodak_512_1 > /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Kodak_512_1.txt
python eval_folder_example.py /data/zhangzf2505/Infinity/dataset/Kodak_512 --model msillm_quality_vlo2 --save_path /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Kodak_512_vlo2 > /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Kodak_512_vlo2.txt

python eval_folder_example.py /data/zhangzf2505/Infinity/dataset/Kodak --model msillm_quality_3 --save_path /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Kodak_3 > /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Kodak_3.txt
python eval_folder_example.py /data/zhangzf2505/Infinity/dataset/Kodak --model msillm_quality_2 --save_path /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Kodak_2 > /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Kodak_2.txt
python eval_folder_example.py /data/zhangzf2505/Infinity/dataset/Kodak --model msillm_quality_1 --save_path /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Kodak_1 > /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Kodak_1.txt
python eval_folder_example.py /data/zhangzf2505/Infinity/dataset/Kodak --model msillm_quality_vlo2 --save_path /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Kodak_vlo2 > /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Kodak_vlo2.txt

python eval_folder_example.py /data/zhangzf2505/Infinity/dataset/Tecnick_768 --model msillm_quality_3 --save_path /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Tecnick_768_3 > /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Tecnick_768_3.txt
python eval_folder_example.py /data/zhangzf2505/Infinity/dataset/Tecnick_768 --model msillm_quality_2 --save_path /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Tecnick_768_2 > /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Tecnick_768_2.txt
python eval_folder_example.py /data/zhangzf2505/Infinity/dataset/Tecnick_768 --model msillm_quality_1 --save_path /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Tecnick_768_1 > /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Tecnick_768_1.txt
python eval_folder_example.py /data/zhangzf2505/Infinity/dataset/Tecnick_768 --model msillm_quality_vlo2 --save_path /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Tecnick_768_vlo2 > /data/zhangzf2505/CompressionMethods/NeuralCompression/projects/illm/output/Tecnick_768_vlo2.txt